<?php $this->partial('navigation', ['user' => $user]) ?>

<main class="container mx-auto pt-10 pb-12 px-4 lg:pb-16 space-y-6">
    <div class="flex justify-between">
        <div>
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Log Information
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">
                Update your game's log.
            </p>
        </div>
    </div>

    <form method="POST" action="<?php echo "/game-logs/{$log->getId()}" ?>">
        <input type="hidden" name="_method" value="PUT">
        <div class="mt-5 border-gray-200">
            <dl class="sm:divide-y sm:divide-gray-200">
                <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                    <dt class="text-sm font-medium text-gray-500">
                        Date
                    </dt>
                    <div class="mt-1">
                        <input type="date" value="<?php echo $log->getDate()->format('Y-m-d') ?>" name="name" id="name" class="px-2 py-1 shadow-sm  focus:outline-none focus:ring-red-500 focus:border-red-500 focus:z-10 block w-full sm:text-sm border border-gray-300 rounded-md">
                    </div>
                </div>
                <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                    <dt class="text-sm font-medium text-gray-500">
                        Description
                    </dt>
                    <div class="mt-1 col-span-2">
                        <textarea id="description" name="description" rows="3" class="px-2 py-1 block w-full shadow-sm  focus:outline-none focus:ring-red-500 focus:border-red-500 focus:z-10 sm:text-sm border border-gray-300 rounded-md"><?php echo $log->getDescription() ?></textarea>
                    </div>
                </div>
            </dl>
        </div>

        <div class="flex justify-end">
            <button onclick="history.back()" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                Cancel
            </button>
            <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-500 hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                Update this log
            </button>
        </div>
    </form>
</main>