<!DOCTYPE html>
<html>

<head>
    <title>Scroll Lock</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1">

    <link rel="shortcut icon" href="/images/scroll_lock_32.png">
    <link href="https://fonts.googleapis.com/css?family=Eagle+Lake" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
</head>

<body class="w-screen h-screen flex flex-col bg-yellow-50">
    <?php $this->yield() ?>

    <script>
        Turbolinks.start()
    </script>
</body>

</html>