<?php $this->partial('navigation', ['user' => $user]) ?>

<form class="max-w-lg mx-auto pt-10 pb-12 px-4 lg:pb-16 space-y-6" action="<?php echo "/characters/{$character->getId()}" ?>" method="POST">
    <input type="hidden" name="_method" value="PUT">

    <div>
        <h1 class="text-lg leading-6 font-medium text-gray-900">
            Character Information
        </h1>
        <p class="mt-1 text-sm text-gray-500">
            Let’s get started by filling in the information below to update your character.
        </p>
    </div>

    <div>
        <label for="name" class="block text-sm font-medium text-gray-700">
            Character Name
        </label>
        <div class="mt-1">
            <input type="text" name="name" id="character_name" value="<?php echo $character->getName() ?>" class="px-2 py-1 block w-full shadow-sm  focus:outline-none focus:ring-red-500 focus:border-red-500 focus:z-10 sm:text-sm border border-gray-300 rounded-md">
        </div>
    </div>

    <div>
        <label for="description" class="block text-sm font-medium text-gray-700">
            Description
        </label>
        <div class="mt-1">
            <textarea id="description" name="description" rows="3" class="px-2 py-1 block w-full shadow-sm  focus:outline-none focus:ring-red-500 focus:border-red-500 focus:z-10 sm:text-sm border border-gray-300 rounded-md"><?php echo $character->getDescription() ?></textarea>
        </div>
    </div>

    <div class="flex justify-end">
        <button onclick="history.back()" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Cancel
        </button>
        <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-500 hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Update this character
        </button>
    </div>
</form>